### ISSUE TITLE
책 정보 열람 시 오류

### ISSUE THREAD

**Issue by hyunbinseo** [YeonsuBaek/libookrary#39]
[검색](https://libookrary.vercel.app/search) 메뉴 진입 후 책을 선택하면 하기 오류가 발생합니다.

(수정) 로그아웃, 로그인 상태에서 공통적으로 발생하는 문제임을 확인했습니다.

> Application error: a server-side exception has occurred (see the server logs for more information).
> Digest: 2247406297

> Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

**Comment by YeonsuBaek** [comment]
[https://libookrary.vercel.app](https://libookrary.vercel.app)

작업 막바지에 push한 내용이 vercel에 적용되지 않아서 생긴 버그에요!
수정했습니다😁
